### ISSUE TITLE
Lab 14 Common Data Service no longer exists

### ISSUE THREAD

**Issue by SergioE-AMS** [Power-Automate-in-a-day/Training-by-the-community#22]
Hello

In step 2 from task 2, it requests add an action List records from the **Common Data Service (current environment)** connector.

This item no longer exists, it was replaced by **List rows [Premium]** from **Microsoft Dataverse** group.

Please update the lab docs.

Thank you,.

**Comment by sergeluca** [comment]
Hello,

thank you for this information; the whole documentation is going to be fully updated ; don't hesitate to send new suggestions !

Cheers



Serge Luca


Business Applications (Power Automate & PowerApps) MVP

Creator of the open-source Power Platform BPM Toolkit

https://github.com/sergeluca/Power-Platform-BPM-Toolkit


Power Platform Associates, Belgium

P: +32 472 885 928

E: ***@***.******@***.***>

Blog<http://sergeluca.wordpress.com/> | Linkedin <http://www.linkedin.com/in/sergeluca> | Twitter <http://www.twitter.com/sergeluca> | Web<http://www.shareql.com/>


[cid:306505e8-2552-4af6-a284-ea662d1268b7]


[cid:dad66d7a-c7c4-476e-b9cb-62a185d85337]
________________________________
From: SergioE-AMS ***@***.***>
Sent: Friday, 22 April 2022 08:43
To: Power-Automate-in-a-day/Training-by-the-community ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Power-Automate-in-a-day/Training-by-the-community] Lab 14 Common Data Service no longer exists (Issue #22)


Hello

In step 2 from task 2, it requests add an action List records from the Common Data Service (current environment) connector.

This item no longer exists, it was replaced by List rows [Premium] from Microsoft Dataverse group.

Please update the lab docs.

Thank you,.
