### ISSUE TITLE
Lab 8. Filter Query

### ISSUE THREAD

**Issue by Rune-70MM** [Power-Automate-in-a-day/Training-by-the-community#24]
On Page 11 Step 21. 
The Problem is:
Filter Query type: **Invoice eq.‘’** 
_And in the following step you have to insert the "InvoiceID"_
I tried it multiple times but it did not work for me. 

For me the following worked **Invoice eq ''**
It is the typewirter apostrophe (') not the punctuation apostrophe (‘) .
I did not need the dot (.) at all :)

The Flow runs without any errors for me with this "solution".

Thanks again for this really impressive training!

**Comment by sergeluca** [comment]
yes, you are right. Fixed. Thank you again ! :-). Typos in this new iteration of the labs.
Serge
