### ISSUE TITLE
Lab 7 Step 18

### ISSUE THREAD

**Issue by josh-barnett** [Power-Automate-in-a-day/Training-by-the-community#3]
On lab 7 following step 18 the user is instructed to enter item()?['InvoiceID'] and is shown a screenshot of the expression field. Then, another screenshot shows the expression field occupied by items('Apply_to_each_Invoice')?['InvoiceID'] . These contradicting screenshots make step 18 confusing to follow.

**Comment by sergeluca** [comment]
Hello @josh-barnett.  you are right, this is a bit confusing. I've fixed & republished the lab. Thank you very much for the feedback ! Let me know if you are ok with this and if I can close the issue.
