### ISSUE TITLE
Confusing picture in Lab 2, task 2.2

### ISSUE THREAD

**Issue by panjkov** [Power-Automate-in-a-day/Training-by-the-community#6]
The picture at the end of 2.2 displays a notification of rejected request.
https://github.com/Power-Automate-in-a-day/Training-by-the-community/blob/master/PDF/Lab%202.%20Approvals%20(Part%201)%20-%20Travel%20Approval.pdf

That is completely opposite of the handled use case, as the guide suggest that the request should be approved. This can confuse beginners. 
In my opinion, this picture should be replaced with picture of approved request, as in that case it would completely be in accordance with the lab narrative

**Comment by sergeluca** [comment]
I've just fixed the issue. Thank you & sorry !

**Comment by panjkov** [comment]
No need to apologize :) You are doing great work here!

I am trying to be constructive so that the materials can be improved.
