### ISSUE TITLE
Lab 3 issues :)

### ISSUE THREAD

**Issue by panjkov** [Power-Automate-in-a-day/Training-by-the-community#7]
Hi, some remarks regarding lab 3:
1. On Page 2, when describing condition for the IF, directions are to check only for exclamation mark ! - however, as you are adding dot (as the end of the sentence) this might be misleading to beginners. I would just remove dot although that would make the sentences in step 3 grammatically incorrect. Those are 3, and sentence in d)
![image](https://user-images.githubusercontent.com/8397641/85873960-2df0ea80-b7d2-11ea-8057-91144a327288.png)
2. On page 4, instead of section 3.2 in the header it is written 3.12
![image](https://user-images.githubusercontent.com/8397641/85874017-46f99b80-b7d2-11ea-975c-d3a3671f37e2.png)

**Comment by sergeluca** [comment]
Thank you Dragan! fixed
