### ISSUE TITLE
Lab 12 unable to add permissions 

### ISSUE THREAD

**Issue by Kandhan-Sekar** [Power-Automate-in-a-day/Training-by-the-community#8]
![image](https://user-images.githubusercontent.com/67395585/86030277-1b9cc980-b9e9-11ea-9768-129bd3f1d076.png)

**Comment by sergeluca** [comment]
Hello Kandhan, thank you for your feedback. In the lab step 13 : 	"Click Grant Consent for <your tenant name>" . I can see in your screenshot that consent has not been given. Let me know how it works

**Comment by Kandhan-Sekar** [comment]
@sergeluca  i dont seem to get that option, which makes me wonder if i am missing some permissions?

**Comment by sergeluca** [comment]
@Kandhan-Sekar what happens if you click the warning messages ?

**Comment by Kandhan-Sekar** [comment]
![image](https://user-images.githubusercontent.com/67395585/86038222-73d9c880-b9f5-11ea-88b6-68ba29514b65.png)
It pops up a info bar to the right,

**Comment by sergeluca** [comment]
@Kandhan-Sekar are you tenant admin?

**Comment by sergeluca** [comment]
@Kandhan-Sekar take a look at this https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent#:~:text=Sign%20in%20to%20the%20Azure,then%20click%20Grant%20admin%20consent.
