### ISSUE TITLE
Lab2. Run failed

### ISSUE THREAD

**Issue by tmwang** [Power-Automate-in-a-day/Training-by-the-community#9]
The flow failed to run. Please see the attached picture.
![image](https://user-images.githubusercontent.com/24721344/87753225-ffee3d00-c7b6-11ea-9c11-effe4babc519.png)

**Comment by sergeluca** [comment]
Hello @tmwang .Are you using a corporate Office 365 or a trial ? This discussion can help https://powerusers.microsoft.com/t5/Using-Flows/Approval-Flow-failed-with-XrmApprovalsGeneralPermissionsError/td-p/451020
